### ISSUE TITLE
提示发送失败

### ISSUE THREAD

**Issue by Gourds** [869339820/Android-LAN_Wake-_PC#1]
安卓手机  安装后填写了mac地址
手机和电脑在同一局域网
提示发送失败

**Comment by 869339820** [comment]
你的问题解决了吗？前面忘记设置Issues提醒了 哈哈.......

**Comment by Gourds** [comment]
> 你的问题解决了吗？前面忘记设置Issues提醒了 哈哈.......

没有解决，是不是mac地址格式有要求呢

**Comment by 869339820** [comment]
代码中 是这样的格式解析的 AA:BB:CC:DD:EE:FF

**Comment by 869339820** [comment]
出现发送失败，其实都是在解析MAC地址异常了，这种情况肯定是MAC地址输错了，比如少输了啥的。

**Comment by Gourds** [comment]
![Screenshot_2020-05-09-10-00-22-176_com zc wake](https://user-images.githubusercontent.com/13073660/81461078-015e2080-91dc-11ea-8db9-a6e5ceb556e8.jpg)
感觉格式应该没问题，会不会存在手机适配的情况，我的是红米k20

**Comment by New-Zero-Zero** [comment]
已处理，重新下载就行了，如果手机上有以前的版本需要卸载下，我替换了APP签名文件。

**Comment by Gourds** [comment]
> 已处理，重新下载就行了，如果手机上有以前的版本需要卸载下，我替换了APP签名文件。

好的，感谢

**Comment by New-Zero-Zero** [comment]
更新版本到雷姆版本且加入了logo更新为雷姆请慢慢欣赏雷姆身姿与眼神

 
![Screenshot_2020-05-09-10-00-22-176_com zc wake](https://github.com/New-Zero-Zero/Android-LAN_Wake-_PC/blob/master/image/1.png?raw=true)

**Comment by Gourds** [comment]
awsl
